### ISSUE TITLE
All users filtred when importing

### ISSUE THREAD

**Issue by JHGBaouns** [Microsoft/MIMPowerShellConnectors#10]
I have set up Lync connector with only four attributes, three in and four out.
All users are filtred out when importing, ou are not.
Lync 2010.
### Importing

I have no Inbound System Scoping Filter set.
Relation between accountName and SamAccountName
Only flowing Enabled, RegistrarPool and SipAddress.
### Outbound

 4 attributes in Outbound.
- DN
- RegistrarPool
- Enabled
- SipAddress
### Error

I have enabled tracelog and gets this in the log.
Its seems strange to search for 9*, any clues or am I on wrong tracks?

```
Method Name : PowerShellRuntime : Initialize
The progress record is parent = -1 id = 1 act = Import-Users stat = Invoking Get-CsUser -LdapFilter '(&(objectCategory=person)(objectClass=user)(msRTCSIP-PrimaryUserAddress=sip:9*))' cur =  pct = -1 sec = -1 type = Processing
```

**Comment by NileshGhodekar** [comment]
Do you have any users that are already Lync enabled? If not, you won't see any in the CS. What you are seeing in the event log is expected and is explained at [https://github.com/Microsoft/MIMPowerShellConnectors/wiki/Lync-Connector-Configuration#paging-filter](https://github.com/Microsoft/MIMPowerShellConnectors/wiki/Lync-Connector-Configuration#paging-filter)

**Comment by JHGBaouns** [comment]
Yes thanks, I see now that I totally missunderstood how the import was suppose to work.
I have a lot of users activated though... looking deeper.

**Comment by JHGBaouns** [comment]
I had some leftover data in my Lab AD from previous installation. After cleaning up my lync attributes I can provision Lync. 
Sorry to bother you.
