### ISSUE TITLE
Lync Connector 

### ISSUE THREAD

**Issue by alexiszp** [Microsoft/MIMPowerShellConnectors#11]
Hello!
1. At setup stage I get this error:
"The validation result returned from the PowerShell compliant server is null"
Can you say there can be error?
1. Does your solution need access to Internet?
   Thanks!

**Comment by NileshGhodekar** [comment]
There should be more detailed error in the event log.

**Comment by alexiszp** [comment]
Yes, I also thinked so, but there is nothing.
Strange.

Also Import of MA is not working, "DTD is prohibited in this XML document"

**Comment by NileshGhodekar** [comment]
There is probably something wrong at the platform level. What version of Windows Server, FIM/MIM, and PowerShell connector you have? Also did you "unblocked" the downloaded zip file before unzipping?

**Comment by alexiszp** [comment]
After reboot it works. Don't understand why.
Nilesh, can you, plese say where I can found "Additional Config Parameter Name" configuration?
Is "SipAddressType" in your documentation is the same with "SipAddressType_Global" in MA, Global Parameters?
Thanks!

**Comment by NileshGhodekar** [comment]
Good. The parameter names will have different suffixes based on which screen you are on, but essentially yes.

**Comment by NileshGhodekar** [comment]
I'm closing this as seems everything is OK now.
