### ISSUE TITLE
LyncConnector Export script bug

### ISSUE THREAD

**Issue by ExhaleSthlm** [Microsoft/MIMPowerShellConnectors#13]
Hi, I found a script bug in Lync Connector Export script.

Error during export was:
![lyncconnectorerror](https://cloud.githubusercontent.com/assets/5760253/23511369/231b875e-ff5d-11e6-9415-d61c1348b4c5.PNG)

It turns out there's an extra single quotation mark on line 465 in the export script that gives the error (highlighted):
![extrasinglequotationmark](https://cloud.githubusercontent.com/assets/5760253/23511518/9816ed8c-ff5d-11e6-8be5-e0f259ee00a6.PNG)

**Comment by NileshGhodekar** [comment]
Thanks Henrik. I've checked in the fixed script. I'll close this issue now.
