### ISSUE TITLE
Skype to AD Attribute Mapping

### ISSUE THREAD

**Issue by thomashouston** [Microsoft/MIMPowerShellConnectors#14]
Hi Nilesh,

Would it be possible to update the Connector Space Design table in the Wiki with the corresponding AD attributes? For example, 'SipAddress' maps to 'msTRCSIP-PrimaryUserAddress'.

Thanks in advance,

Tom

**Comment by NileshGhodekar** [comment]
Can you please explain the purpose for this? I'm not sure if there is any public documentation of AD attributes used by Skype and for what purpose (four or five of them like msTRCSIP-PrimaryUserAddress are "well-known"),  but the Connector is solely concerned with the API's (PowerShell cmdlets) offered by Skype and is agnostic to where Skype puts or stores the data, so I don't see a need for it to be part of the connector documentation.

**Comment by NileshGhodekar** [comment]
Closing for now. If there is an official documentation on the subject, please share the link and we can add it to the wiki.
