### ISSUE TITLE
MarkDown type in Wiki

### ISSUE THREAD

**Issue by SimonWahlin** [Microsoft/MIMPowerShellConnectors#16]
Hi,

I'm not sure of the best way to contribute to information in the wiki since I haven't found a way to do a pull request on a wiki. I've cloned the wiki and pushed it to my [own repository](https://github.com/SimonWahlin/MIMPowerShellConnectors-wiki) where I've made a few changes. If there is a better way to contribute, please steer me in the right direction.

There are typos in the MarkDown for the following pages:
[https://github.com/Microsoft/MIMPowerShellConnectors/wiki/Flat-File-Connector-Setup-and-Configuration](https://github.com/Microsoft/MIMPowerShellConnectors/wiki/Flat-File-Connector-Setup-and-Configuration)
[https://github.com/Microsoft/MIMPowerShellConnectors/wiki/Flat-File-Connector-Troubleshooting](https://github.com/Microsoft/MIMPowerShellConnectors/wiki/Flat-File-Connector-Troubleshooting)

I've changed them in my fork in this commit: [Fixed MarkDown syntax](https://github.com/SimonWahlin/MIMPowerShellConnectors-wiki/commit/4c2831c4d11ab26c75a0d1eaad71f1341ffaeb37)

Best regards,
Simon

**Comment by NileshGhodekar** [comment]
Thanks Simon. A better way than this is much more complex. This is far simpler. Thanks again. Done.
