### ISSUE TITLE
Timeframe

### ISSUE THREAD

**Issue by ExhaleSthlm** [Microsoft/MIMPowerShellConnectors#2]
Sorry, I feel this is the wrong channel for asking this but I haven't found a better way.
However my question is what timeframe you have for releasing the not yet released ones?
I'm in a project and very interested in having a look at the Sharepoint and Homedrive connectors if they will suit my needs.

//Henrik Nilsson

**Comment by NileshGhodekar** [comment]
Hi Henrik, right now it's just a wish list. The actual work to make it happen is not prioritised.

**Comment by ExhaleSthlm** [comment]
Thanks!
I thought you basically had these connectors created already and just needed to maybe do some cleanup and stuff before release.

**Comment by NileshGhodekar** [comment]
Cleanup yes, but also creating wiki's for these connectors is a big work.

**Comment by quanghung231078** [comment]
eWallet apps (hunglai231078@gmail.com)
