### ISSUE TITLE
Question about logging

### ISSUE THREAD

**Issue by weyto** [Microsoft/MIMPowerShellConnectors#20]
Hello everybody,

does anyone know how we can enable debug and verbose logging on a PowerShell Management Agent?
At the wiki on the Flat file MA is a printscreen about the RunProfile with the option DebugPreferences and VerbosePreferences.
This isn't showing up in the latest version.
When I perform the config over the miisserver.exe.config at the debug section for ConnectorsLog I can perform some verbose logging, but this doesn't Printout the Write-Verbose and Write-Debug commands.

Best regards,
Thomas

**Comment by NileshGhodekar** [comment]
You could use the instructions provided for Lync Connector under section "[Enable Tracing Event Log](https://github.com/Microsoft/MIMPowerShellConnectors/wiki/Lync-Connector-Troubleshooting#enable-tracing-event-log)".

**Comment by NileshGhodekar** [comment]
Closing this as I'm hoping this is resolved.

**Comment by weyto** [comment]
Hi Nilesh

Sorry for the delay. Yes it was my mistake.
Interesting when Write-Debug is called over the Import-Script (in a paging szenario), there is an issue.
After every paged cycle the entries will be created more then once.
So on the first paged import all events are showing up once.
On the second paged import, the entries are showing up twice. On the third step there are showing up 3 times and so on.

But i think this is not a problem of the Lync MA implementation or on my implementation with an other application. It looks like this is an issue on the PowerShell MA implementation it self.

What i asked myself to, is how can done the configuration that only Write-Debug or Write-Verbose are logged? On the miisserver.exe.config i can only say Verbose, None or Error. Or have i miss anything?

**Comment by NileshGhodekar** [comment]
You have Information and Warning as well, but I believe both Write-Debug and Write-Verbose both log at the Verbose level only. I'd provided a feedback to the PG to distinguish these based on different Event ID's  say EventID 100 for Debug and 101 for Verbose so that we can filter them easily, but I'm not sure if they ever implemented it.
