### ISSUE TITLE
Dev to Prod Migratoin Issues - Partition and Containers

### ISSUE THREAD

**Issue by bpalfaro** [Microsoft/MIMPowerShellConnectors#22]
Hello,

When migrating a sync server configuration from Dev to Prod, updating the Lync MA connection information and setting the new partition doesn't seem to work or stick.  If you open up the MA after this, the Dev values remain.  

To work around this, we exported the MA in-place from production, did a find and replace of the Dev partition to the Prod partition values in the XML, and then updated the management agent.  An example would be to find and replace DC=contosolab,DC=com to DC=contoso,DC=com within the MA XMl and then re-import.  

The MA seems to run a Full Import profile correctly now, but the UI still does not reflect the selected containers at this point.  The partitions are correct.

Please provide any thoughts or recommendations?

Thanks,
Bryan

**Comment by NileshGhodekar** [comment]
Hi This issue affect many non-PowerShell MA as well. I believe, post import, you should be able to open MA properties and make the appropriate selections. I'm closing this issue as there is not much that can be done here as this is basically a MIM product issue.
